### ISSUE TITLE
Bug in election code

### ISSUE THREAD

**Issue by Swamp-Ig** [Ialdabaoth/ModuleManager#2]
I think the election won't work right if you get two copies of the same version:

In OnGUI the line:

```
if (eligible.Any(a => 
    a.assembly.GetName().Version.CompareTo(currentAssembly.GetName().Version) == 1))
```

should probably be:

```
if (eligible.Any(a => 
     a.assembly.GetName().Version.CompareTo(currentAssembly.GetName().Version) == 1
   || a.assembly.Location.CompareTo(currentAssembly.Location) < 0))
```

This essentially selects the last one in the path

Edit: Might be better to choose the first one really

**Comment by sarbian** [comment]
I changed for 2.0.2. Thanks
